### ISSUE TITLE
Test for AddLoan Component

### ISSUE THREAD

**Issue by te4-andre-skvarc** [itggot-TE4/Yabs#587] opened 2020-12-21 10:45 UTC
## ✨ Feature request
Add test coverage for Addloan component

### 📜 Acceptance Criteria

- [ ]  Add a test that logs in on the pages and loans a book!

**Comment by te4-adrian-almetun-smeds** [comment] 2021-01-14 13:36
Duplicate of #479

**Closed by te4-adrian-almetun-smeds** 2021-01-14 13:36 UTC
Labels: comp: frontend, point: 1, type:test🚨
