### ISSUE TITLE
Loan books

### ISSUE THREAD

**Issue by TE4-Filip-Liljenberg** [itggot-TE4/Yabs#376] opened 2020-12-09 14:36 UTC
## ✨ Feature request
The user clicks on "Låna bok" button and an input bar pops up where you should write down your books code, after that you press the "Låna" button and you are done.
### 📇 User story
As a user I want to be able to loan a book by scanning the books code.

### 📜 Acceptance Criteria
- [x] investigate existing functionality
- [x] You can click on the "Låna bok" button and a input bar pops up.
- [x] You can write your books code into the input bar and then push  the "Låna" button.
- [ ] The book will now be shown as loaned.
### 💡 Additional context
add css as mockup.

**Comment by itggot-linus-styren** [comment] 2020-12-16 13:59
Talk to @itggot-TE4/red-team if this a duplicate of #422 or if it can be combined.

**Comment by te4-andre-skvarc** [comment] 2020-12-17 09:35
The functionality is there but it doesn't work. Therefore I will start a repair, investigating why it doesn't work.

**Closed** 2020-12-21 08:21 UTC
Labels: point: 3, team: blue, type:feature✨, type:investigation🔎
